micronaut:
  application:
    name: aws
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
  object-storage:
    aws:
      default:
        bucket: '${OBJECT_STORAGE_BUCKET}'
otel:
  traces:
    exporter: otlp
    propagator: 'tracecontext, baggage, xray'
  exclusions:
  - /health
netty:
  default:
    allocator:
      max-order: 3
