apiVersion: v1
kind: Namespace
metadata:
  name: gcn-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcn-app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec: 
      containers:
      - name: app
        image: "bom.ocir.io/apaccpt01/gcn-demo-oci:${IMG_TAG}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - name: app
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gcn-app-lb
  labels:
    app: app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: app